services:
  app:
    volumes:
      - ./src:/app/src
    command: ["uv", "run", "uvicorn", "--app-dir", "./src", "--reload", "--host", "0.0.0.0", "--port", "5100", "main:app"]
    environment:
      - NODE_ENV=development