services:
  app:
    build:
      target: development
    image: subtranslator:dev
    container_name: subtranslator-dev
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development